FROM php:8.2-fpm
#php:8.2-fpm

COPY --from=composer:2.5.5 /usr/bin/composer /usr/local/bin/composer

ADD php/php.ini /usr/local/etc/php/conf.d/default.ini

RUN apt-get update && apt-get install -y libmcrypt-dev \
    && apt-get install -y libzip-dev \
    && apt-get install -y libpq-dev
RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_pgsql
RUN docker-php-ext-install zip
RUN docker-php-ext-install exif
RUN docker-php-ext-install opcache
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pgsql pdo_pgsql

COPY ./app/site/vendor /var/www/html/vendor
COPY ./app/site/bootstrap /var/www/html/bootstrap
COPY ./app/site/storage/framework /var/www/html/storage/framework
COPY ./app/site/storage/logs /var/www/html/storage/logs

RUN chown -R www-data:www-data /var/www/html/storage \
  && chown -R www-data:www-data /var/www/html/bootstrap/cache \
  && chmod -R 777 /var/www/html/storage \
  && chmod -R 666 $(find /var/www/html/storage -type f) \
  && chmod -R 777 /var/www/html/bootstrap/cache \
  && chmod -R 666 $(find /var/www/html/bootstrap/cache -type f)

WORKDIR /var/www/html

CMD ["php-fpm"]
