version: '3.9'

networks:
  app-network:
    name: laravel-network
    driver: bridge

services:
  composer:
    tty: true
    container_name: laravel-composer
    image: laravel-composer:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-composer
    entrypoint: ["/bin/sh","-c"]
    command:
      - composer create-project laravel/laravel site
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network