version: '3.9'

networks:
  app-network:
    name: laravel-network
    driver: bridge

volumes:
  postgres-data:
    name: laravel-db-data
  pgadmin-data:
    name: laravel-pgadmin-data
  redis-data:
    name: laravel-redis-data
  dbbackup-data:
    name: laravel-dbbackup-data
  except-data:
    name: laravel-except-data

services:
  composer:
    tty: true
    container_name: laravel-composer
    image: laravel-composer:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-php
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - composer update --ignore-platform-reqs
    volumes:
      - ./app/site:/var/www/html
      - except-data:/var/www/html/node_modules
    networks:
      - app-network
  nginx:
    restart: unless-stopped
    container_name: laravel-nginx
    image: laravel-nginx:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8000:80"
    volumes:
      - ./app/site/public:/var/www/html/public
      - ./app/site/bootstrap:/var/www/html/bootstrap
      - ./app/site/storage:/var/www/html/storage
    depends_on:
      - composer
      - php
      - db
      - redis
    links:
      - php
      - db
      - composer
    networks:
      - app-network
  redis:
    restart: unless-stopped
    container_name: laravel-redis
    image: laravel-redis:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-redis
    ports:
      - "8001:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
  db:
    restart: unless-stopped
    container_name: laravel-db
    image: laravel-db:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "8002:5432"
    environment:
      #- POSTGRES_HOST=localhost
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dfhsfs3434235
    volumes:
      - postgres-data:/var/lib/postgresql/data
    #      - ./db/data:/var/lib/postgresql/data
    networks:
      - app-network
  php:
    tty: true
    restart: unless-stopped
    container_name: laravel-php
    image: laravel-php:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - ":9000"
    volumes:
      - ./app/site:/var/www/html
      - except-data:/var/www/html/node_modules
      - except-data:/var/www/html/vendor
    depends_on:
      - composer
      - redis
    command:
      - -c
      - |
        chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache;
        chmod -R 777 /var/www/html/storage;
        chmod -R 666 $(find /var/www/html/storage -type f);
        chmod -R 777 /var/www/html/bootstrap/cache;
        chmod -R 666 $(find /var/www/html/bootstrap/cache -type f);
    networks:
      - app-network
  redis-admin:
    restart: unless-stopped
    container_name: laravel-predis
    image: laravel-redisadmin:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-redisadmin
    environment:
      REDIS_1_HOST: redis
      REDIS_1_PORT: 6379
    ports:
      - "8004:80"
    depends_on:
      - redis
    networks:
      - app-network
  pgadmin:
    restart: unless-stopped
    container_name: laravel-pgadmin
    image: laravel-pgadmin:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-pgadmin
    ports:
      - '8007:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: "alex@alex.alex"
      PGADMIN_DEFAULT_PASSWORD: "adminadmin"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
  pgbackups:
    restart: unless-stopped
    image: laravel-dbbackup:latest
    user: postgres:postgres
    build:
      context: .
      dockerfile: Dockerfile-dbbackup
    volumes:
      - ./db/data:/backups
      - dbbackup-data:/var/lib/postgresql/data
    links:
      - db:db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dfhsfs3434235
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 12h00m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81
    networks:
      - app-network
  queue:
    restart: unless-stopped
    container_name: laravel-queue
    image: laravel-queue:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./app/site:/var/www/html
      - except-data:/var/www/html/node_modules
    depends_on:
      - composer
      - db
      - php
    entrypoint: [ 'php', 'artisan', 'queue:work' ]
    networks:
      - app-network
  cron:
    restart: unless-stopped
    container_name: laravel-cron
    image: laravel-cron:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./app/site:/var/www/html
      - except-data:/var/www/html/node_modules
    depends_on:
      - composer
      - db
      - php
    entrypoint: [ 'php', 'artisan', 'schedule:work' ]
    networks:
      - app-network
  artisan:
    container_name: laravel-artisan
    image: laravel-artisan:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./app/site:/var/www/html
      - except-data:/var/www/html/node_modules
    depends_on:
      - composer
      - db
    entrypoint: [ 'php', 'artisan' ]
    networks:
      - app-network
  migrate:
    container_name: laravel-migrate
    image: laravel-migrate:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./app/site:/var/www/html
      - except-data:/var/www/html/node_modules
    depends_on:
      - composer
      - db
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        php artisan migrate
#        php artisan db:seed
    networks:
      - app-network
  npm:
    tty: true
    container_name: laravel-npm
    image: laravel-npm:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-npm
    ports:
      - "3000:3000"
    volumes:
      - ./app/site/public:/home/node/project/public
      - ./app/site/lang:/home/node/project/lang
      - ./app/site/resources:/home/node/project/resources
      - ./app/site/storage/app:/home/node/project/storage/app
      - ./app/site/.env:/home/node/project/.env
      - ./app/site/package.json:/home/node/project/package.json
      - ./app/site/tsconfig.json:/home/node/project/tsconfig.json
      - ./app/site/vite.config.js:/home/node/project/vite.config.js
#    entrypoint: ["npm", "run", "build", "--"] #, "--", #"--host", "0.0.0.0"
#    environment:
#      APP_ENV: production
    entrypoint: [ "npm", "run", "dev", "--" ]
    environment:
      APP_ENV: local
    depends_on:
      - composer
      - php
    networks:
      - app-network
  npm-files:
    tty: true
    container_name: laravel-npm-files
    image: laravel-npm-files:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-npm
    ports:
      - ":3010"
    entrypoint: ["npm", "install"]
    volumes:
      - ./app/site/package.json:/home/node/project/package.json
      - ./app/site/node_modules:/home/node/project/node_modules
    depends_on:
      - composer
      - php
    networks:
      - app-network