#FROM composer:2.5.5

# composer:2.5.5
#CMD ["composer", "update"]


FROM php:8.2-fpm
#php:8.2-fpm

ADD php/php.ini /usr/local/etc/php/conf.d/default.ini

COPY --from=composer:2.5.5 /usr/bin/composer /usr/local/bin/composer

RUN apt-get update && apt-get install -y libmcrypt-dev \
    && apt-get install -y libzip-dev \
    && apt-get install -y libpq-dev
RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_pgsql
RUN docker-php-ext-install zip
RUN docker-php-ext-install exif
RUN docker-php-ext-install opcache
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pgsql pdo_pgsql

WORKDIR /var/www/html

