version: '3.9'

networks:
  app-network:
    name: laravel-network
    driver: bridge

volumes:
  node-modules-composer:
    name: laravel-data-node-modules

services:
  composer-install:
    tty: true
    container_name: laravel-composer
    image: laravel-composer:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-composer
    entrypoint: ["/bin/sh","-c"]
    command:
      - composer create-project laravel/laravel site
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
  composer-update:
    container_name: laravel-composer
    image: laravel-composer:latest
    user: root:root
    build:
      context: .
      dockerfile: Dockerfile-php
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - composer update --ignore-platform-reqs
    volumes:
      - ./app/site:/var/www/html
      - node-modules-composer:/var/www/html/node_modules
    networks:
      - app-network